### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by DachunKai** [ctom2/colie#5]
Can you kindly provide the pretrained model? Thanks.

**Comment by ctom2** [comment]
CoLIE is a NIR-based model, which means that the model weights need to be optimized per image; hence, there is no specific pre-trained model that could be shared (it would cover low-light enhancement of only one specific image). 

The model is designed to be very lightweight, allowing the enhancement of each image to take only a couple of seconds. You can try the model on any image of your choosing with [this demo](https://colab.research.google.com/github/ctom2/colie).

**Comment by DachunKai** [comment]
Thank you for the information—this is very interesting!
